# Generated by Django 4.0.4 on 2022-04-22 16:56

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_album_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(upload_to='musics/', validators=[core.validators.validate_is_audio]),
        ),
    ]
